# Generated by Django 5.2.5 on 2025-09-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_developer_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AlterField(
            model_name='developer',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
