# Generated by Django 5.2.5 on 2025-09-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_remove_skill_category_alter_developer_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
